_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.8.5
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.8.5
            "5": 0.18.2
            "8":
                - 5
            "12": 0.18.2
            "13": linux-x86_64
activation:
    value: tanh
epochs:
    value: 1000
hidden_layer_1:
    value: 128
hidden_layer_2:
    value: 64
learning_rate:
    value: 0.1
optimizer:
    value: sgd
